### ISSUE TITLE
add github actions example

### ISSUE THREAD

**Issue by kopax-polyconseil** [webdriverio/appium-boilerplate#132]
**Pre-check**

I'm aware that I can [edit the docs](https://github.com/webdriverio/native-demo-app) and submit a pull request

**Describe the improvement**

I'd like to report Missing documentation

**Example available**

- [x] iOS app
- [x] iOS browser
- [x] Android app
- [x] Android browser
- [x] Desktop browser safari
- [x] Desktop browser chrome

**Description of the improvement / report**

Hi guys, someone of yours hinted me to this project to get my configuration done. It is really interesting to read that repo, but reason why we choosed appium for our e2e testing was the hability to run in a CI process and I've been trying to run test in:

- iOS-browser : https://github.com/webdriverio/appium-boilerplate/pull/134
- iOS-native  : https://github.com/webdriverio/appium-boilerplate/pull/134
- Android-browser : https://github.com/webdriverio/appium-boilerplate/pull/135
- Android-native : https://github.com/webdriverio/appium-boilerplate/pull/134
- Browser safari: https://github.com/webdriverio/appium-boilerplate/pull/138
- Browser chrome: https://github.com/webdriverio/appium-boilerplate/pull/138

I know this is a typescript boilerplate and conf, but it could be nice to share efforts and maintain a certain validity for this repo by adding a way to check if this boilerplate is still applicable.

**Comment by christian-bromann** [comment]
I agree. Testing this repository makes sense and is what we do in other boilerplates too. Any contributions to this are welcome!

**Comment by kopax-polyconseil** [comment]
This is a configuration that work for `android.web`:

```yml
name: Tests e2e Android Chrome

on:
  workflow_dispatch:
    inputs:
      tbd:
        description: "tbd"
        required: false
        type: string

jobs:
  e2e-android-chrome:
    strategy:
      matrix:
        include:
#          - chromedriverVersion: "74.0.3729.6"
#            apiLevel: 30
#            emuTag: google_apis
          - chromedriverVersion: "74.0.3729.6"
            apiLevel: 29
            emuTag: google_apis
    #          - chromedriverVersion: "2.44"
    #            apiLevel: 28
    #            emuTag: default
    #          - chromedriverVersion: "2.28"
    #            apiLevel: 25
    #            emuTag: default
    #          - chromedriverVersion: "2.20"
    #            apiLevel: 23
    #            emuTag: default

    env:
      CI: true
      ANDROID_AVD: Nexus6P
      APPIUM_TEST_SERVER_PORT: 4723
      APPIUM_TEST_SERVER_HOST: 0.0.0.0
      _FORCE_LOGS: 1
    # No hardware acceleration is available for emulators on Ubuntu:
    # https://github.com/marketplace/actions/android-emulator-runner#can-i-use-this-action-on-linux-vms
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: |
          mkdir apps
          wget https://github.com/webdriverio/native-demo-app/releases/download/v0.4.0/Android-NativeDemoApp-0.4.0.apk -P apps
      - run: |
          npm config set legacy-peer-deps true
          npm install -g appium@next
          npm install --chromedriver_version="${{ matrix.chromedriverVersion }}"
          npm install --no-save mjpeg-consumer
        name: Install dev dependencies
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: |
          cwd=$(pwd)
          pushd "$cwd"
          cd ~
          appium driver install uiautomator2
          nohup appium server \
            --port=$APPIUM_TEST_SERVER_PORT \
            --address=$APPIUM_TEST_SERVER_HOST \
            --relaxed-security \
            2>&1 > "$cwd/appium.log" &
          popd
        name: Start Appium server
      - run: nohup adb logcat > logcat.log &
        name: Capture logcat
      - uses: reactivecircus/android-emulator-runner@v2
        name: e2e_api${{ matrix.apiLevel }}
        with:
          script: yarn android.browser
          avd-name: ${{ env.ANDROID_AVD }}
          sdcard-path-or-size: 1500M
          api-level: ${{ matrix.apiLevel }}
          disable-spellchecker: true
          target: ${{ matrix.emuTag }}
          arch: x86
          profile: Nexus 6P
      - name: Save logcat output
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: logcat-api${{ matrix.apiLevel }}
          path: logcat.log
      - name: Save server output
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: appium-api${{ matrix.apiLevel }}
          path: appium.log
```

This is a configuration that work for `android.app`:

```yml
name: Tests e2e Android Native

on:
  workflow_dispatch:
    inputs:
      tbd:
        description: "tbd"
        required: false
        type: string

jobs:
  e2e-android-native:
    strategy:
      matrix:
        include:
#          - chromedriverVersion: "74.0.3729.6"
#            apiLevel: 30
#            emuTag: google_apis
          - chromedriverVersion: "74.0.3729.6"
            apiLevel: 29
            emuTag: google_apis
    #          - chromedriverVersion: "2.44"
    #            apiLevel: 28
    #            emuTag: default
    #          - chromedriverVersion: "2.28"
    #            apiLevel: 25
    #            emuTag: default
    #          - chromedriverVersion: "2.20"
    #            apiLevel: 23
    #            emuTag: default

    env:
      CI: true
      ANDROID_AVD: Nexus6P
      APPIUM_TEST_SERVER_PORT: 4723
      APPIUM_TEST_SERVER_HOST: 0.0.0.0
      _FORCE_LOGS: 1
    # No hardware acceleration is available for emulators on Ubuntu:
    # https://github.com/marketplace/actions/android-emulator-runner#can-i-use-this-action-on-linux-vms
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: yarn install
      - run: |
          mkdir apps
          wget https://github.com/webdriverio/native-demo-app/releases/download/v0.4.0/Android-NativeDemoApp-0.4.0.apk -P apps
      - run: |
          npm config set legacy-peer-deps true
          npm install -g appium@next
          npm install --chromedriver_version="${{ matrix.chromedriverVersion }}"
          npm install --no-save mjpeg-consumer
        name: Install dev dependencies
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: |
          cwd=$(pwd)
          pushd "$cwd"
          cd ~
          appium driver install uiautomator2
          nohup appium server \
            --port=$APPIUM_TEST_SERVER_PORT \
            --address=$APPIUM_TEST_SERVER_HOST \
            --relaxed-security \
            2>&1 > "$cwd/appium.log" &
          popd
        name: Start Appium server
      - run: nohup adb logcat > logcat.log &
        name: Capture logcat
      - uses: reactivecircus/android-emulator-runner@v2
        name: e2e_api${{ matrix.apiLevel }}
        with:
          script: yarn android.app
          avd-name: ${{ env.ANDROID_AVD }}
          sdcard-path-or-size: 1500M
          api-level: ${{ matrix.apiLevel }}
          disable-spellchecker: true
          target: ${{ matrix.emuTag }}
          arch: x86
          profile: Nexus 6P
      - name: Save logcat output
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: logcat-api${{ matrix.apiLevel }}
          path: logcat.log
      - name: Save server output
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: appium-api${{ matrix.apiLevel }}
          path: appium.log

```

I am not able to get the same results on iOS yet, and I will have to add selenium-webdriver as this code base also is for a webapplication with react-native-web.

I have an estimate of 3weeks to integrate those so I am not sure I can dig right now to contribute, but I would definitly do it if I can achieve my priorties first. Any advice would help save time, for instance:

- I can't move `tsconfig.json` into `e2e/tsconfig.json`  , `e2e` being my root directory for e2e, it includes `tests` and `config` and I can't move forward until I found a way to do it
- I have no example on how to start iOS simulator properly in github action. I have timeout when running tests and I don't know what that means, this is a PR example https://github.com/pass-culture/pass-culture-app-native/pull/3876

Any help is always welcome
